main: com.joshlucem.airwavechat.AirwaveChat
name: AirwaveChat
version: 2.0.0
api-version: 1.20
folia-supported: true
authors: [joshlucem]
website: https://github.com/joshlucem/AirwaveChat
description: Radio communication plugin with proximity chat, signal degradation and FM/AM frequency-based channels for Paper/Spigot servers.

commands:
  connect:
    description: Connect to a frequency.
    usage: /connect FM/AM <frequency>
    aliases: [c, radio, tune]
    permission: airwavechat.user
  disconnect:
    description: Disconnect from your current frequency.
    usage: /disconnect
    aliases: [dc, leave, tune-off]
    permission: airwavechat.user
  frequencies:
    description: Manage and view frequencies.
    usage: /frequencies [list FM/AM <page>|current|info <frequency>|top]
    aliases: [freq, freqs, f]
    permission: airwavechat.user
  airwavechat:
    description: Main AirwaveChat command.
    usage: /airwavechat <reload|about|help>
    aliases: [awc, airchat]
    permission: airwavechat.admin

permissions:
  airwavechat.user:
    description: Allows using AirwaveChat user commands
    default: true
  airwavechat.admin:
    description: Allows using AirwaveChat administrator commands
    default: op

